#!/bin/sh
# Backup Ubuntu Device Script
#
# Goal: backup all user data and a list of apps
# todo: Restore script ;)
#
# Assumptions:
#  * Device has ssh enabled
#  * This machine has an ssh key which is on the device

if [ "$#" -ne 1 ]; then
    echo "Specify hostname or IP address of device"
    echo "e.g. 'buds 192.168.1.20'"
    exit 1
fi

DATESTART=$(date +%Y%m%d-%H%M%S)
BACKUPDIR="$HOME/buds/backup/$DATESTART"
LOGFILE=$BACKUPDIR/backup.log
CLICKFILE="$BACKUPDIR/clicks.list"
DEVICEUSER="phablet"
HOST="$1"
mkdir -p $BACKUPDIR

log() {
        echo $(date +%Y%m%d-%H%M%S) : $* | tee -a $LOGFILE
}

# TODO HERE
# Check we have the tools we need to run the backup (rsync / tee)
# check host is up
# check host is actually an ubuntu device
# Count how many files and how much data will be backed up
# Lots of checking for each of these steps to handle failures

# Get device code name
log "Get device code name"
DEVICENAME=$(ssh $DEVICEUSER@$HOST getprop ro.product.name)
if [ "$DEVICENAME" = "" ]; then
  log "Failed to get device code name"
  exit 1
fi
log "Got device code name: $DEVICENAME"

# Get device serial number
log "Get device serial number"
DEVICESERIAL=$(ssh $DEVICEUSER@$HOST getprop ro.serialno)
if [ "$DEVICESERIAL" = "" ]; then
  log "Failed to get device serial number"
  exit 2
fi
log "Got device serial number: $DEVICESERIAL"

# Set final backup file name
COMPRESSEDBACKUP=$BACKUPDIR/$DEVICENAME-$DEVICESERIAL.tgz

log "Determine disk space used on device"
DEVICESPACE=$(ssh $DEVICEUSER@$HOST "du -bs /home/phablet/" | awk '{ print $1}')
log "Finished determining disk space used on device"

log "Determine free space on current machine"
DESKTOPSPACE=$(df -B1 --output=avail  $BACKUPDIR | tail -n 1)
log "Finished determining free space on current machine"

# Check if we have enough disk space in $BACKUPDIR for the backup (roughly 2x size)
# if DESKTOPSPACE > DEVICESPACE*2 then okay!
DOUBLEDEVICESPACE=$(expr $DEVICESPACE \* 2)
log "Approximate disk space used on device: $DEVICESPACE"
log "Approximate free space on backup disk: $DESKTOPSPACE"
log "Approximate freespace need for backup: $DOUBLEDEVICESPACE"

# Rudimentary check for 2x space used on device on desktop
if [ "$DOUBLEDEVICESPACE" -gt "$DESKTOPSPACE" ]; then
  log "Insufficient free space on backup device: $DESKTOPSPACE smaller than $DOUBLEDEVICESPACE"
  exit 3
fi

# Get list of applications installed on device
log "Get list of installed apps from device"
ssh $DEVICEUSER@$HOST 'click list' > $CLICKFILE
log "Finished getting list of installed apps from device"

# Start backup

log "Copying files from device"
rsync -az --info=progress2 -e ssh $DEVICEUSER@$HOST:/home/$DEVICEUSER $BACKUPDIR | tee -a $LOGFILE
if [ "$?" = "0" ]; then
  log "Finished copying files from device"
else
  log "Copying files from device FAILED"
  exit 4
fi

# Compress backup
log "Compressing backup"
tar czf $COMPRESSEDBACKUP $BACKUPDIR/$DEVICEUSER
if [ "$?" = "0" ]; then
  log "Finished compressing backup to $COMPRESSEDBACKUP"
  log "Deleting uncompressed backup files from $BACKUPDIR/$DEVICEUSER"
  rm -rf $BACKUPDIR/$DEVICEUSER
  if [ "$?" = "0" ]; then
    log "Finished deleting uncompressed backup files from $BACKUPDIR/$DEVICEUSER"
  else
    log "Problem deleting uncompressed backup files from $BACKUPDIR/$DEVICEUSER"
    exit 5
  fi
else
  log "Compressing files FAILED"
  exit 6
fi
